#!/usr/bin/env ruby

# http://www.iheartquotes.com/api/v1/random

['gmail', 'typhoeus'].each do |gem|
  begin
    require gem
  rescue LoadError
    puts "You need to install #{gem}: gem install #{gem} ruby-gmail"
    exit!(1)
  end
end

config_file = "#{ENV['HOME']}/.sandwich"
unless File.exist?(config_file)
  puts "You need to type the sandwich makers email, your email and password (one per line) into `~/.sandwich`"
  puts "Example:"
  puts "sandwicher@generalthings.com"
  puts "youremail@generalthings.com"
  puts "password"
  exit!(1)
end

sandwich_maker,email,password = File.read(config_file).split("\n")

quote = Typhoeus::Request.get("http://www.iheartquotes.com/api/v1/random")

msg = quote.body.split("\n")
msg.pop

gmail = Gmail.new(email, password)

gmail.deliver do
  to "#{sandwich_maker}"
  subject "Favor pleaseeee! :)"
  text_part do
    body "Please sir,\n
    Could you make me a sandwich?\n
    #{msg.join("\n")}
    \nThank you!"
  end
end

gmail.logout
